services:
    m88og8okssw0sckoswgcog8s-000110085103:
        image: 'm88og8okssw0sckoswgcog8s:9298711d293635a108ac992d3e2bd41b9c0b8d63'
        container_name: m88og8okssw0sckoswgcog8s-000110085103
        restart: unless-stopped
        expose:
            - '3000'
        networks:
            coolify:
                aliases:
                    - m88og8okssw0sckoswgcog8s-000110085103
        mem_limit: '0'
        memswap_limit: '0'
        mem_swappiness: 60
        mem_reservation: '0'
        cpus: 0.0
        cpu_shares: 1024
        env_file:
            - .env
        labels:
            - traefik.enable=true
            - traefik.http.middlewares.gzip.compress=true
            - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
            - traefik.http.routers.http-0-m88og8okssw0sckoswgcog8s.entryPoints=http
            - traefik.http.routers.http-0-m88og8okssw0sckoswgcog8s.middlewares=gzip
            - 'traefik.http.routers.http-0-m88og8okssw0sckoswgcog8s.rule=Host(`www.puttbrothers.com`) && PathPrefix(`/`)'
            - traefik.http.routers.http-0-m88og8okssw0sckoswgcog8s.service=http-0-m88og8okssw0sckoswgcog8s
            - traefik.http.routers.http-1-m88og8okssw0sckoswgcog8s.entryPoints=http
            - traefik.http.routers.http-1-m88og8okssw0sckoswgcog8s.middlewares=gzip
            - 'traefik.http.routers.http-1-m88og8okssw0sckoswgcog8s.rule=Host(`puttbrothers.com`) && PathPrefix(`/`)'
            - traefik.http.routers.http-1-m88og8okssw0sckoswgcog8s.service=http-1-m88og8okssw0sckoswgcog8s
            - traefik.http.routers.http-2-m88og8okssw0sckoswgcog8s.entryPoints=http
            - traefik.http.routers.http-2-m88og8okssw0sckoswgcog8s.middlewares=gzip
            - 'traefik.http.routers.http-2-m88og8okssw0sckoswgcog8s.rule=Host(`www.puttbrothers.uk`) && PathPrefix(`/`)'
            - traefik.http.routers.http-2-m88og8okssw0sckoswgcog8s.service=http-2-m88og8okssw0sckoswgcog8s
            - traefik.http.routers.http-3-m88og8okssw0sckoswgcog8s.entryPoints=http
            - traefik.http.routers.http-3-m88og8okssw0sckoswgcog8s.middlewares=gzip
            - 'traefik.http.routers.http-3-m88og8okssw0sckoswgcog8s.rule=Host(`puttbrothers.uk`) && PathPrefix(`/`)'
            - traefik.http.routers.http-3-m88og8okssw0sckoswgcog8s.service=http-3-m88og8okssw0sckoswgcog8s
            - traefik.http.routers.http-4-m88og8okssw0sckoswgcog8s.entryPoints=http
            - traefik.http.routers.http-4-m88og8okssw0sckoswgcog8s.middlewares=gzip
            - 'traefik.http.routers.http-4-m88og8okssw0sckoswgcog8s.rule=Host(`www.puttbrothers.de`) && PathPrefix(`/`)'
            - traefik.http.routers.http-4-m88og8okssw0sckoswgcog8s.service=http-4-m88og8okssw0sckoswgcog8s
            - traefik.http.routers.http-5-m88og8okssw0sckoswgcog8s.entryPoints=http
            - traefik.http.routers.http-5-m88og8okssw0sckoswgcog8s.middlewares=gzip
            - 'traefik.http.routers.http-5-m88og8okssw0sckoswgcog8s.rule=Host(`puttbrothers.de`) && PathPrefix(`/`)'
            - traefik.http.routers.http-5-m88og8okssw0sckoswgcog8s.service=http-5-m88og8okssw0sckoswgcog8s
            - traefik.http.routers.http-6-m88og8okssw0sckoswgcog8s.entryPoints=http
            - traefik.http.routers.http-6-m88og8okssw0sckoswgcog8s.middlewares=gzip
            - 'traefik.http.routers.http-6-m88og8okssw0sckoswgcog8s.rule=Host(`www.puttbrothers.ch`) && PathPrefix(`/`)'
            - traefik.http.routers.http-6-m88og8okssw0sckoswgcog8s.service=http-6-m88og8okssw0sckoswgcog8s
            - traefik.http.routers.http-7-m88og8okssw0sckoswgcog8s.entryPoints=http
            - traefik.http.routers.http-7-m88og8okssw0sckoswgcog8s.middlewares=gzip
            - 'traefik.http.routers.http-7-m88og8okssw0sckoswgcog8s.rule=Host(`puttbrothers.ch`) && PathPrefix(`/`)'
            - traefik.http.routers.http-7-m88og8okssw0sckoswgcog8s.service=http-7-m88og8okssw0sckoswgcog8s
            - traefik.http.services.http-0-m88og8okssw0sckoswgcog8s.loadbalancer.server.port=3000
            - traefik.http.services.http-1-m88og8okssw0sckoswgcog8s.loadbalancer.server.port=3000
            - traefik.http.services.http-2-m88og8okssw0sckoswgcog8s.loadbalancer.server.port=3000
            - traefik.http.services.http-3-m88og8okssw0sckoswgcog8s.loadbalancer.server.port=3000
            - traefik.http.services.http-4-m88og8okssw0sckoswgcog8s.loadbalancer.server.port=3000
            - traefik.http.services.http-5-m88og8okssw0sckoswgcog8s.loadbalancer.server.port=3000
            - traefik.http.services.http-6-m88og8okssw0sckoswgcog8s.loadbalancer.server.port=3000
            - traefik.http.services.http-7-m88og8okssw0sckoswgcog8s.loadbalancer.server.port=3000
            - 'caddy_0.encode=zstd gzip'
            - 'caddy_0.handle_path.0_reverse_proxy={{upstreams 3000}}'
            - 'caddy_0.handle_path=/*'
            - caddy_0.header=-Server
            - 'caddy_0.try_files={path} /index.html /index.php'
            - 'caddy_0=http://www.puttbrothers.com'
            - 'caddy_1.encode=zstd gzip'
            - 'caddy_1.handle_path.1_reverse_proxy={{upstreams 3000}}'
            - 'caddy_1.handle_path=/*'
            - caddy_1.header=-Server
            - 'caddy_1.try_files={path} /index.html /index.php'
            - 'caddy_1=http://puttbrothers.com'
            - 'caddy_2.encode=zstd gzip'
            - 'caddy_2.handle_path.2_reverse_proxy={{upstreams 3000}}'
            - 'caddy_2.handle_path=/*'
            - caddy_2.header=-Server
            - 'caddy_2.try_files={path} /index.html /index.php'
            - 'caddy_2=http://www.puttbrothers.uk'
            - 'caddy_3.encode=zstd gzip'
            - 'caddy_3.handle_path.3_reverse_proxy={{upstreams 3000}}'
            - 'caddy_3.handle_path=/*'
            - caddy_3.header=-Server
            - 'caddy_3.try_files={path} /index.html /index.php'
            - 'caddy_3=http://puttbrothers.uk'
            - 'caddy_4.encode=zstd gzip'
            - 'caddy_4.handle_path.4_reverse_proxy={{upstreams 3000}}'
            - 'caddy_4.handle_path=/*'
            - caddy_4.header=-Server
            - 'caddy_4.try_files={path} /index.html /index.php'
            - 'caddy_4=http://www.puttbrothers.de'
            - 'caddy_5.encode=zstd gzip'
            - 'caddy_5.handle_path.5_reverse_proxy={{upstreams 3000}}'
            - 'caddy_5.handle_path=/*'
            - caddy_5.header=-Server
            - 'caddy_5.try_files={path} /index.html /index.php'
            - 'caddy_5=http://puttbrothers.de'
            - 'caddy_6.encode=zstd gzip'
            - 'caddy_6.handle_path.6_reverse_proxy={{upstreams 3000}}'
            - 'caddy_6.handle_path=/*'
            - caddy_6.header=-Server
            - 'caddy_6.try_files={path} /index.html /index.php'
            - 'caddy_6=http://www.puttbrothers.ch'
            - 'caddy_7.encode=zstd gzip'
            - 'caddy_7.handle_path.7_reverse_proxy={{upstreams 3000}}'
            - 'caddy_7.handle_path=/*'
            - caddy_7.header=-Server
            - 'caddy_7.try_files={path} /index.html /index.php'
            - 'caddy_7=http://puttbrothers.ch'
            - caddy_ingress_network=coolify
            - coolify.managed=true
            - coolify.version=4.0.0-beta.442
            - coolify.applicationId=10
            - coolify.type=application
            - coolify.name=m88og8okssw0sckoswgcog8s
            - coolify.resourceName=puttbrothers-website-v2
            - coolify.projectName=puttbrothers
            - coolify.serviceName=puttbrothers-website-v2
            - coolify.environmentName=production
            - coolify.pullRequestId=0
networks:
    coolify:
        external: true
        name: coolify
        attachable: true
